Switch to cssbox CSS parser.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/bin/sh
 cd "$(dirname "${BASH_SOURCE[0]}")"
 mkdir -p /disk1/java/maven-repo/com/innoventsolutions
-mvn install:install-file \
+if ! mvn install:install-file \
   -Dfile="./target/report-engine-0.0.1-SNAPSHOT.jar" \
   -Dsources="./target/report-engine-0.0.1-SNAPSHOT-sources.jar" \
   -DgroupId="com.innoventsolutions" \
@@ -9,4 +9,7 @@ mvn install:install-file \
   -Dversion="0.0.1-SNAPSHOT" \
   -Dpackaging=jar \
   -DgeneratePom=true \
-  -DlocalRepositoryPath=/disk1/java/maven-repo
+  -DlocalRepositoryPath=/disk1/java/maven-repo > install.log 2> install.err.log; then
+  	echo "install failed - see install.log"
+  	exit 1
+fi
